# Generated by Django 5.0.3 on 2024-08-21 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0007_alter_mail_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='client',
            new_name='subscriber',
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 9, 13, 21, 30221)),
        ),
    ]
