# Generated by Django 5.0.3 on 2024-08-21 15:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0008_rename_client_mail_subscriber_alter_mail_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 15, 19, 45, 642771)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
